const ACTIONS = {
    ADD_TODO: "ADD_TODO",
    TOGGLE_TODO_COMPLETED: "TOGGLE_TODO_COMPLETED",
    DELETE_TODO: "DELETE_TODO",
    SET_TODO_DUE_DATE: "SET_TODO_DUE_DATE",
    RESET_TODOS_DATE_FILTER: "RESET_TODOS_DATE_FILTER",
    SET_IS_FILTERED: "SET_IS_FILTERED",
    LOAD_MORE_TODOS: "LOAD_MORE_TODOS",
    CHANGE_TODO_PRIORITY: "CHANGE_TODO_PRIORITY"
}

export default ACTIONS